### ISSUE TITLE
Line Charts - Time-based charts not working using MySQL

### ISSUE THREAD

**Issue by hermanschutte** [ForestAdmin/forest-laravel#16]
Time-based charts encounter an issue on MySQL because of the use of `to_char` which doesn't exist on MySQL.

**Comment by arnaudbesnier** [comment]
You're right, we tested the liana with Postgresql database where time-based charts work well.
MySQL does not have the powerful methods to group by time-periods.

We'll fix this in the next version.

**Comment by arnaudbesnier** [comment]
This PR https://github.com/ForestAdmin/forest-laravel/pull/20 adds the Line Charts support using MySQL.

**Comment by arnaudbesnier** [comment]
The fix is available in the new 0.0.5 version.

**Comment by hermanschutte** [comment]
Still not working unfortunately. Here is the error I get:

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '."created_at", '%Y-%m-%d 00:00:00') as date, COUNT(*) as value from `user_widget' at line 1 (SQL: select DATE_FORMAT("user_widgets"."created_at", '%Y-%m-%d 00:00:00') as date, COUNT(*) as value from `user_widgets` left join `widgets` as `t0` on `user_widgets`.`widget_id` = `t0`.`id` left join `users` as `t1` on `user_widgets`.`user_id` = `t1`.`id` group by `date` order by `date` asc)`

**Comment by arnaudbesnier** [comment]
Hey @hermanschutte, sorry for the regression (it was working with version 0.0.6).
I just released a new version that will make charts work properly on MySQL.

**Comment by hermanschutte** [comment]
Thanks @arnaudbesnier, it's working now.
